### ISSUE TITLE
sudo: cd: command not found

### ISSUE THREAD

**Issue by fawqsir** [mateuszpiela/bounca-docker#1]
created a docker-compose file:

```
version: "3.9"
services:
  bounca-app:
    image: mateuszpiela/bounca
    environment:
      DB_NAME: ${POSTGRES_DB:-bounca}
      DB_USER: ${POSTGRES_USER:-bounca}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-bounca}
      DB_HOST: ${POSTGRES_HOST:-bounca-db}
      DB_PORT: 5432

      #MAIL_HOST=""
      #MAIL_PORT=""
      #MAIL_USER=""
      #MAIL_PASSWORD=""
      #MAIL_CONNECTION=""
      #MAIL_ADMIN=""
      #MAIL_FROM=""

      CE_KEY_ALGO: rsa                     # ed25519, rsa
      EMAIL_VERIFICATION: optional         # mandatory, optional, off
      DOMAIN: ${CONTAINER_NAME:-bounca}.${DOMAIN_NAME}
    expose:
      - 80
      - 443
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      - "traefik.http.services.${CONTAINER_NAME:-bounca}.loadbalancer.server.port=80"       
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}.entrypoints=web"
#      - "traefik.http.routers.${CONTAINER_NAME:-bounca}.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/${CONTAINER_NAME:-bounca}`)" 
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}.rule=Host(`${CONTAINER_NAME:-bounca}.${DOMAIN_NAME}`)" 

      # use to redirect http to https
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}-secure.entrypoints=websecure"
#      - "traefik.http.routers.${CONTAINER_NAME:-bounca}-secure.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/${CONTAINER_NAME:-bounca}`)"
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}-secure.rule=Host(`${CONTAINER_NAME:-bounca}.${DOMAIN_NAME}`)"
 
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}-secure.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}-secure.tls.certresolver=tlsresolver"
      
      - "traefik.http.routers.${CONTAINER_NAME:-bounca}-secure.middlewares=https-sslheaders"
    networks:
      - traefik_proxy
      - internal
#    volumes:
#      - ./data/ssl:/ssl
#      - ./data/bounca:/etc/bounca
    depends_on:
      - bounca-db

  bounca-db:
    image: postgres:16-alpine
    container_name: ${CONTAINER_NAME:-bounca}-db
    restart: unless-stopped
    volumes:
      - ./data/postgres-16:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bounca}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bounca}
      POSTGRES_DB: ${POSTGRES_DB:-bounca}'
    networks:
      - internal


networks:
  traefik_proxy:
    external: true
  internal:
    driver: bridge
    internal: true
    attachable: false
```

When I run this compose file the logs show the following entrypoint.sh lines are not working:

    sudo -u www-data cd /srv/www/bounca && env/bin/python3 manage.py migrate
    sudo -u www-data cd /srv/www/bounca && echo "yes" | env/bin/python3 manage.py collectstatic --clear
    sudo -u www-data cd /srv/www/bounca && env/bin/python3 python3 manage.py site $DOMAIN

Log output:
bounca-db            | 2023-09-28 19:10:28.452 UTC [1] LOG:  database system is ready to accept connections
bounca-bounca-app-1  | bounca-db:5432 - accepting connections
bounca-bounca-app-1  | sudo: cd: command not found
bounca-bounca-app-1  | sudo: cd: command not found
bounca-bounca-app-1  | sudo: cd: command not found
bounca-bounca-app-1  | 2023-09-28 19:10:29,334 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in theconfig file to avoid this message.
bounca-bounca-app-1  | 2023-09-28 19:10:29,340 INFO RPC interface 'supervisor' initialized
bounca-bounca-app-1  | 2023-09-28 19:10:29,340 CRIT Server 'unix_http_server' running without any HTTP authentication checking
bounca-bounca-app-1  | 2023-09-28 19:10:29,340 INFO supervisord started with pid 7
bounca-bounca-app-1  | 2023-09-28 19:10:30,343 INFO spawned: 'nginx' with pid 16
bounca-bounca-app-1  | 2023-09-28 19:10:30,345 INFO spawned: 'uwsgi' with pid 17
bounca-bounca-app-1  | [uWSGI] getting INI configuration from /etc/uwsgi/apps-enabled/bounca.ini
bounca-bounca-app-1  | 2023-09-28 19:10:31,482 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bounca-bounca-app-1  | 2023-09-28 19:10:31,482 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

Sorry I do not have a solution.
